name: Publish GitHub Pages
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: npm install
    - run: npm run publish
    - name: Commit changes to GitHub Pages
      uses: EndBug/add-and-commit@v7
      with:
        branch: 'gh-pages'
